version: "3.8"

services:
  postgres:
    image: postgres:13
    container_name: websocket_service
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: pg_websocket_service
    ports:
      - "5432:5432"